# Broadcasting (Transmicion)

In [1]:
import numpy as np

arreglo = np.array([[1,2,3],
                   [4,5,6]])

In [2]:
"""  Multiplicaion por un escalar  """
arreglo_prod = arreglo * 3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [4]:
"""  Adicion de arreglos  """
arreglo1 = np.array([[1,2,3],
                   [4,5,6]])
arreglo2 = np.array([[7,8,9],
                   [10,11,12]])
arreglo3 = arreglo1 + arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
"""  Evaluacion de condiciones  """
arreglo1 = np.array([[1,2,3],
                    [4,5,6]])

arreglo1 > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [9]:
"""  Las funciones de python no estan vectorizadas de origen  """
arreglo = np.array(["Numpy", "manejo","vectorizacion"])
len(arreglo) > 5

False

In [10]:
"""  conversion para vectorizar la funcion len  """
len_vec = np.vectorize(len)
len_vec(arreglo) > 5

array([False,  True,  True])

# Broadcasting en renglones

In [11]:
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

# Broadcasting en columnas

In [14]:
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))  ## Se ajusta el arreglo apra que tena dos renglones y una columna

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [15]:
"""  ejm no factible  """
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1])

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [16]:
"""  Voltear un arreglo  """
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [3.1,3.2,3.3]])
np.flip(arreglo)

array([[3.3, 3.2, 3.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [17]:
"""  Trasposicion  """
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [3.1,3.2,3.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 3.1],
       [1.2, 2.2, 3.2],
       [1.3, 2.3, 3.3]])

# Ejercicio

In [30]:
np.array([[1,2], [3,4]]) * np.array([[5],[10]])

array([[ 5, 10],
       [30, 40]])

In [32]:
np.array([[1,2], [3,4]]) - np.array([[5, 10]])

array([[-4, -8],
       [-2, -6]])