# Métodos y operaciones de Numpy

In [5]:
import numpy as np
accidentes = np.array([[0,1,1],
                      [1,0,1],
                      [1,3,2],
                      [2,2,0]])

# Mediante el uso de un arreglo NumPy determine 

In [6]:
"""  a) El numero total de accidentes durtante los 4 años  """
accidentes.sum()

np.int64(14)

In [8]:
"""  b) El numero total de accidentes por area(por columna)  """
acciden_area = accidentes.sum(axis = 0)
acciden_area

array([4, 6, 4])

In [12]:
print("Los accidentes totales del area 1 son:",acciden_area[0])
print("Los accidentes totales del area 2 son:",acciden_area[1])
print("Los accidentes totales del area 3 son:",acciden_area[2])

Los accidentes totales del area 1 son: 4
Los accidentes totales del area 2 son: 6
Los accidentes totales del area 3 son: 4


In [16]:
"""  c) El numero total de accidentes por año(renglon)  """
acciden_año = accidentes.sum(axis=1)
acciden_año

array([2, 2, 6, 4])

In [17]:
"""  Conservacion de dimensiones  """
acciden_año = accidentes.sum(axis=1, keepdims= True)
acciden_año

array([[2],
       [2],
       [6],
       [4]])

In [18]:
print("Los accidentes totales del año 1 son:",acciden_año[0])
print("Los accidentes totales del año 2 son:",acciden_año[1])
print("Los accidentes totales del añp 3 son:",acciden_año[2])
print("Los accidentes totales del añp 4 son:",acciden_año[3])

Los accidentes totales del año 1 son: [2]
Los accidentes totales del año 2 son: [2]
Los accidentes totales del añp 3 son: [6]
Los accidentes totales del añp 4 son: [4]


In [19]:
"""  d) El numero maximo y minimo de accidentes por area y año  """
maximo = accidentes.max()
minimo = accidentes.min()

print(f"Maximo de accidentes: {maximo}")
print(f"Minimo de accidentes: {minimo}")

Maximo de accidentes: 3
Minimo de accidentes: 0


In [21]:
"""  e) El numero promedio de accidentes por area y año  """
promedio = accidentes.mean()
print(f"El promedio de accidentes es: {promedio}")

El promedio de accidentes es: 1.1666666666666667


# Operaciones Vectorizadas

In [23]:
"""  Determine la suma descrita en la imagen de abajo mediante:
a) Un ciclo en Python
b) Una función vectorizada de NumPy  """

arreglo = np.array([[1,2,3],
                   [4,5,6]])

dimensiones = arreglo.shape
print(dimensiones[0])  ## Renglones
print(dimensiones[1])  ## Columnas
print(arreglo[0][0])  ## Primer elemento de la tabla

2
3
1


In [30]:
"""  Inciso a  """
import time
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range(dimensiones[0]):
    for columnas in range(dimensiones[1]):
        arreglo_final[renglon][columnas] = arreglo[renglon][columnas] + 3
print(arreglo_final)

fin = time.time()
print("Tiempo total de ejecucion (Segs)", fin - inicio)

[[4. 5. 6.]
 [7. 8. 9.]]
Tiempo total de ejecucion (Segs) 0.00047469139099121094


In [31]:
"""  Inciso b  """
import time
inicio = time.time()

arreglo_final = arreglo + 3
print(arreglo_final)

fin = time.time()
print("Tiempo total de ejecucion (Segs)", fin - inicio)


[[4 5 6]
 [7 8 9]]
Tiempo total de ejecucion (Segs) 0.0002532005310058594
