# Indexacion

In [1]:
import numpy as np

In [2]:
"""  Indexacion de un solo elemento  """
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
## Extraccion de elementos en forma ascendente
x[2]

np.int64(2)

In [4]:
## Extraccion de elementos en forma descentende
x[-2]

np.int64(8)

In [5]:
x.shape = (2,5) # Conversion del arreglo a formato bidimencional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x[1,3] # Extraccion del elemento con indice 1 en renglon e indice 3 en columna

np.int64(8)

In [7]:
x[1][3] # Alternativa de extraccion

np.int64(8)

In [9]:
x[1][-1]

np.int64(9)

In [10]:
x[0]

array([0, 1, 2, 3, 4])

In [11]:
"""  Cortes en arreglos  """
x= np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2] # Formato: 'start:stop:step'

array([1, 3, 5])

In [12]:
x[-2:10] # Cortes dek arreglo de adelante hacia atras

array([8, 9])

In [13]:
x[-3:3:-1] # Corte del arreglo de adelante hacia atas, iniciando tres posiciones del final y retrocediendo hasta tener como limite el numero 3

array([7, 6, 5, 4])

In [15]:
"""  Definicion de un nuevo arreglo  """
x = np.arange(10,1,-1) # Forma descendente
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [16]:
"""  Extraccion de eletementos especificos del arreglo  """
x[np.array([3,3,1,8])] # Extraccion de elementos con indices 3,3,1,8

array([7, 7, 9, 2])

In [17]:
x[np.array([3,3,-3,8])] # Extraccion de elementos con indices 3,3,4,8

array([7, 7, 4, 2])

In [18]:
"""  Extraccion basada en pares  """
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [19]:
y[np.array([0,2,4]), np.array([0,1,2])] # Extraccion de coordenadas (0,0) (2,1) (4,2)

array([ 0, 15, 30])

# Union de arreglos

In [21]:
"""  Concatenacion de vectores  """
arr = np.concatenate(([1,2,3], [4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [22]:
"""  Apilado vertical de vectores  """
np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
"""  Concatenacion de matrices  """
mat_1 = np.array([[1,2,3],[4,5,6]])
mat_2 = np.array([[1,1,1],[2,2,2]])
np.concatenate((mat_1,mat_2), axis = 0) # Stackea

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [29]:
np.concatenate((mat_1,mat_2), axis = 1) # Concatena verticalmente

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [27]:
np.concatenate((mat_1,mat_2), axis = None) # Concatena en una

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])