# Numpy

In [1]:
import numpy as np

In [3]:
"""  Creacion de arreglo a partir de una lista  """
lista1 = [1,2,3,4,5]
arreglo1 = np.array(lista1)  ## Convertimos la lista en un arreglo
arreglo1

array([1, 2, 3, 4, 5])

In [4]:
type(arreglo1)

numpy.ndarray

In [18]:
"""  Creacion de un arreglo a partir de una lista de listas"""
"""  Bi-dimencional"""
lista2 = [[1,2,3],
            [4,5,6],
            [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
"""  La desventaja de las listas es que pueden contener diversos tipos de datos"""
list1 = ["a", True, 2]
list1

['a', True, 2]

In [13]:
"""  Por ende los arreglos solo pueden tener un tipo de dato"""
"""  Convierte los valores a tipo cadena para usar menos memoria en el sitema"""
arreglo = np.array(list1)
arreglo

array(['a', 'True', '2'], dtype='<U21')

In [14]:
"""  Creacion de arreglos con ceros  """
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
"""  Creacion de arreglo con numeros aleatorios uniformes entre 0 y 1  """
np.random.random((3,2))

array([[0.99304125, 0.71604599],
       [0.77944604, 0.14034415],
       [0.11935292, 0.97732735]])

In [16]:
"""  Creacion de arreglo en un rango  """
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
"""  Creacion de un arreglo multi-dimencional"""
arreglo1 = np.array([[1,2],
                    [5,7]])
arreglo2 = np.array([[8,9],
                    [5,7]])
arreglo3 = np.array([[3,4],
                    [5,7]])

In [20]:
arreglo_3D = np.array([arreglo1, arreglo2, arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[3, 4],
        [5, 7]]])

In [21]:
arreglo_3D.shape

(3, 2, 2)

In [22]:
"""  Conversion de arreglo multi-dimencional a uni-dimencional  """
list2 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
arreglo2 = np.array(list2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
"""  Cambio de dimension de un arreglo  """
arreglo = np.array([[1,2],
                   [3,4],
                   [5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
"""  Ejem de error al momento de cambiar la dimension del arreglo"""
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

# Tipos de datos de NumPy
int64 |
int32 |
float64 |
float32

In [26]:
np.array([1.25,2.43,200.88]).dtype

dtype('float64')

In [27]:
arreglo_int = np.array([[1,2,3], [4,5,6]])
arreglo_int.dtype

dtype('int64')

In [28]:
arreglo_string = np.array(["Introduccion", "a", "la", "casa"])
arreglo_string.dtype

dtype('<U12')

In [30]:
"""  Cambio del largo del parametro  """
arreglo = np.array([1.25,2.43,200.88], dtype = np.float32)
arreglo.dtype

dtype('float32')

In [31]:
"""  Cambio de tipo de arreglo  """
arreglo_boleano = np.array([[True, False]], dtype = np.bool_)
arreglo_boleano.dtype

dtype('bool')

In [32]:
arreglo = arreglo_boleano.astype(np.int32)  ## Cambio del tipo de valor
arreglo

array([[1, 0]], dtype=int32)

In [33]:
"""  Homologacion del tipo por jerarquia  """
np.array([0,50,50.8]).dtype

dtype('float64')

In [34]:
np.array([False, 42]).dtype

dtype('int64')